<?php

function dcx_integration_form_entity_browser_media_entity_browser_form_alter(&$form) {

  if (!empty($form['widget']['dropzone']['#type']) && $form['widget']['dropzone']['#type'] == 'dcxdropzone') {
    $form['draggables'] = [
      '#theme' => 'item_list',
      '#title' => 'Draggables for testing provided by dcx_integration_debug module.',
      '#items' => [
        ['#markup' => '<div class="item single">Single image</div>'],
        ['#markup' => '<div class="item list">List of images</div>'],
      ],
      '#attributes' => ['class' => 'draggable']
    ];

    $form['#attached']['library'][] = 'dcx_integration_debug/draggable';
  }

}
