<?php

/**
 * @param $form
 */
function dcx_entity_browser_form_entity_browser_image_browser_form_alter(&$form) {

  if (!empty($form['widget']['dropzone']['#type']) && $form['widget']['dropzone']['#type'] == 'dcxdropzone') {
    $form['actions'] = [];
  }
}

/**
 * Implements hook_preprocess_views_view().
 */
function dcx_entity_browser_preprocess_views_view(&$variables) {
  if ($variables['view']->id() === 'gallery_browser' || $variables['view']->id() === 'image_browser') {
    $variables['view_array']['#attached']['library'][] = 'media_entity_browser/view';
  }
}
